fix: change for issue #36
RobinTheHood/modified-stripe pull request #38
Opened 2023-10-29 21:00 UTC by RobinTheHood

2023-10-30 10:23 UTC, grandeljay requested changes

2023-10-30 10:23 UTC, grandeljay commented on src/admin/includes/extra/javascript/rth_stripe.php
> +require_once DIR_FS_DOCUMENT_ROOT . '/includes/extra/functions/rth_modified_std_module.php';
This line is not required. The Stripe module has the std-module as a dependency which already handles auto loading for us.

Could you remove it please?

2023-10-30 10:23 UTC, grandeljay commented on src/admin/includes/extra/javascript/rth_stripe.php
> +            // console.log(tab);
While you're at it, can you also please remove all `console.log`'s?

2023-10-30 14:51 UTC, RobinTheHood commented
Thanks for your review. I have processed your comments and made two new commits.

2023-10-31 11:32 UTC, grandeljay approved these changes
LGTM

2023-10-31 11:33 UTC, merged